language: go

go:
  - "1.14"

before_install:
  - go get -t -v ./...

script:
  - go test ./pkg/... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
